// demo/react/src/VoiceWidget.jsx
import { useState, useEffect } from "react";
import { useRhino } from "@picovoice/rhino-web-react";

import rhinoModelParams from "./rhino_params";

export default function VoiceWidget() {
  const [accessKey, setAccessKey] = useState("");

  const {
    inference,
    contextInfo,
    isLoaded,
    isListening,
    error,
    init,
    process,
    release,
  } = useRhino();

  const rhnInit = async () => {
    await init(
      accessKey,
      { publicPath: "clock_wasm.rhn" },
      { base64: rhinoModelParams },
    );
  }

  const rhnProcess = async () => {
    await process()
  }

  const rhnRelease = async () => {
    await release()
  }

  return (
    <div className="voice-widget">
      <h2>VoiceWidget</h2>
      <h3>
        <label>
          AccessKey obtained from{" "}
          <a href="https://console.picovoice.ai/">Picovoice Console</a>:
          <input
            type="text"
            name="accessKey"
            onChange={(value) => setAccessKey(value.target.value)}
            disabled={isLoaded}
          />
        </label>
        <button className="start-button" onClick={() => rhnInit()} disabled={isLoaded || accessKey.length === 0}>
          Start Rhino
        </button>
      </h3>
      <h3>Rhino Loaded: {JSON.stringify(isLoaded)}</h3>
      <h3>Listening: {JSON.stringify(isListening)}</h3>
      <h3>Error: {JSON.stringify(error !== null)}</h3>
      {error && accessKey && (
        <p className="error-message">{JSON.stringify(error)}</p>
      )}

      <br />
      <button
        onClick={() => rhnProcess()}
        disabled={error || isListening || !isLoaded}
      >
        Process
      </button>
      <button
        onClick={() => rhnRelease()}
        disabled={error || isListening || !isLoaded}
      >
        Release
      </button>

      <h3>Inference:</h3>
      {inference && <pre>{JSON.stringify(inference, null, 2)}</pre>}
      <hr />
      <h3>Context Info:</h3>
      <pre>{contextInfo}</pre>
    </div>
  );
}

// demo/angular/src/app/voice_widget.component.ts
import { Component, OnDestroy } from '@angular/core';
import { Subscription } from 'rxjs';

import { RhinoInference } from '@picovoice/rhino-web';
import { RhinoService } from '@picovoice/rhino-angular';

// @ts-ignore
import rhinoParams from '../lib/rhino_params';

@Component({
  selector: 'app-voice-widget',
  templateUrl: './voice_widget.component.html',
  styleUrls: ['./voice_widget.component.scss']
})
export class VoiceWidget implements OnDestroy {
  private contextInfoSubscription: Subscription;
  private inferenceSubscription: Subscription;
  private isLoadedSubscription: Subscription;
  private isListeningSubscription: Subscription;
  private errorSubscription: Subscription;

  contextInfo: string | null = null;
  inference: RhinoInference | null = null;
  isLoaded = false;
  isListening = false;
  error: Error | string | null = null;

  constructor(private rhinoService: RhinoService) {
    this.contextInfoSubscription = rhinoService.contextInfo$.subscribe(
      contextInfo => {
        this.contextInfo = contextInfo;
      });
    this.inferenceSubscription = rhinoService.inference$.subscribe(
      inference => {
        this.inference = inference;
      });
    this.isLoadedSubscription = rhinoService.isLoaded$.subscribe(
      isLoaded => {
        this.isLoaded = isLoaded;
      });
    this.isListeningSubscription = rhinoService.isListening$.subscribe(
      isListening => {
        this.isListening = isListening;
      });
    this.errorSubscription = rhinoService.error$.subscribe(
      error => {
        this.error = error;
      });
  }

  ngOnDestroy(): void {
    this.contextInfoSubscription.unsubscribe();
    this.inferenceSubscription.unsubscribe();
    this.isLoadedSubscription.unsubscribe();
    this.isListeningSubscription.unsubscribe();
    this.errorSubscription.unsubscribe();
    this.rhinoService.release();
  }

  public async rhnInit(accessKey: string): Promise<void> {
    if (accessKey.length >= 0) {
      await this.rhinoService.release();
      try {
        await this.rhinoService.init(
          accessKey,
          { publicPath: 'assets/clock_wasm.rhn' },
          { base64: rhinoParams }
        );
      }
      catch (error: any) {
        this.error = error;
      }
    }
  }

  public async rhnProcess(): Promise<void> {
    await this.rhinoService.process();
  }

  public async rhnRelease(): Promise<void> {
    await this.rhinoService.release();
  }
}

<div class="voice-widget">
  <h1>VoiceWidget</h1>
    <h3>
    <label>
      AccessKey obtained from
      <a href="https://picovoice.ai/console/">Picovoice Console</a>:
      <input
        type="text"
        name="accessKey"
        [disabled]="isLoaded"
        #accessKey
      />
    </label>
    <button class="start-button" (click)="initEngine(accessKey.value)" [disabled]="isLoaded">
      Start Rhino
    </button>
  </h3>
  <h3>Dynamic Import Loaded: {{ isChunkLoaded }}</h3>
  <h3>Rhino Loaded: {{ isLoaded }}</h3>
  <h3>Listening: {{ isListening }}</h3>
  <h3>Error: {{ isError }}</h3>
  <p class="error-message" *ngIf="isError">{{ errorMessage }}</p>
  <h3>Talking: {{ isTalking }}</h3>

  <br />
  <button (click)="start()" [disabled]="isError || isListening || !isLoaded">Start</button>
  <button (click)="pause()" [disabled]="isError || !isListening || !isLoaded">Pause</button>
  <button (click)="stop()" [disabled]="isError || !isListening || !isLoaded">Stop</button>
  <button
    (click)="pushToTalk()"
    [disabled]="isError || !isListening || isTalking || !isLoaded"
  >
    Push to Talk
  </button>
  <h3>Inference:</h3>
  <pre *ngIf="inference !== null">{{ inference | json }}</pre>
  <hr />
  <h3>Context Info:</h3>
  <pre>{{ contextInfo }}</pre>
</div>
